services:
  - type: web
    name: aytekin-auto-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npx concurrently "node server.js" "node scripts/scraper.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3001
